services:
  app:
    image: nginx
    ports:
      - "80:80"

  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http app:80 --log stdout
    depends_on:
      - app
    ports:
      - "4040:4040"
